export const MASTER_KEY = "admin_masterdata_v1";
export const MASTER_VERSION_KEY = "admin_masterdata_version";

export const MASTER_TYPES = [
  { key: "company", label: "Company" },
  { key: "brand", label: "Brand" },
  { key: "country", label: "Country" },
  { key: "level", label: "Level" },
  { key: "connectionType", label: "Connection Type" },
  { key: "connectionShape", label: "Connection Shape" },
  { key: "screwdriverShape", label: "Screwdriver Shape" },
  { key: "headShape", label: "Head Shape" },
  { key: "bodyShape", label: "Body Shape" },
  { key: "apexShape", label: "Apex Shape" },
  { key: "officialDistributor", label: "Official Distributor" },
];

// ⭐ ตั้งค่า version ของ seed (เปลี่ยนเลขนี้เมื่อแก้ seed)
const CURRENT_SEED_VERSION = "v10.0";

// seed ตัวอย่าง (แก้ได้ตามที่อยากใส่จริง)
const seed = {
  company: [
    { id: 1, name: "CAMLOG Biotechnologies AG", status: "Active" },
    { id: 2, name: "Neobiotech Co., Ltd.", status: "Active" },
    { id: 3, name: "OSSTEM IMPLANT CO., LTD.", status: "Active" },
    { id: 4, name: "Dentium Co. Ltd.", status: "Active" },
  ],
  brand: [
    // CAMLOG brands - 4 models
    { id: 1, name: "CAMLOG", status: "Active", companyId: 1, modelCount: 4 },
    { id: 2, name: "CAMLOG SCREW", status: "Active", companyId: 1, modelCount: 4 },
    { id: 3, name: "CAMLOG PIONEER", status: "Active", companyId: 1, modelCount: 4 },
    // Neobiotech brands - 5 models
    { id: 4, name: "NEOBIOTECH", status: "Active", companyId: 2, modelCount: 5 },
    { id: 5, name: "NEOBIOTECH MAX", status: "Active", companyId: 2, modelCount: 5 },
    { id: 6, name: "NEOBIOTECH NURI", status: "Active", companyId: 2, modelCount: 5 },
    // OSSTEM brands - 5 models
    { id: 7, name: "OSSTEM TS", status: "Active", companyId: 3, modelCount: 5 },
    { id: 8, name: "OSSTEM TSX", status: "Active", companyId: 3, modelCount: 5 },
    { id: 9, name: "OSSTEM TUA", status: "Active", companyId: 3, modelCount: 5 },
    // Dentium brands - 2 models
    { id: 10, name: "DENTIUM IMPLANTIUM", status: "Active", companyId: 4, modelCount: 2 },
    { id: 11, name: "DENTIUM ASTRA", status: "Active", companyId: 4, modelCount: 2 },
    { id: 12, name: "DENTIUM XIVE", status: "Active", companyId: 4, modelCount: 2 },
  ],
  model: [
    // CAMLOG models
    { id: 1, name: "CAMLOG PROGRESSIVE-LINE", status: "Active", brandId: 1 },
    { id: 2, name: "CAMLOG SCREW-LINE", status: "Active", brandId: 1 },
    { id: 3, name: "CONELOG PROGRESSIVE-LINE", status: "Active", brandId: 1 },
    { id: 4, name: "CONELOG SCREW-LINE", status: "Active", brandId: 1 },
    // CAMLOG SCREW models
    { id: 5, name: "CAMLOG SCREW PRO", status: "Active", brandId: 2 },
    { id: 6, name: "CAMLOG SCREW STANDARD", status: "Active", brandId: 2 },
    { id: 7, name: "CONELOG SCREW PRO", status: "Active", brandId: 2 },
    { id: 8, name: "CONELOG SCREW STANDARD", status: "Active", brandId: 2 },
    // CAMLOG PIONEER models
    { id: 9, name: "PIONEER IMPLANT I", status: "Active", brandId: 3 },
    { id: 10, name: "PIONEER IMPLANT II", status: "Active", brandId: 3 },
    { id: 11, name: "PIONEER IMPLANT III", status: "Active", brandId: 3 },
    { id: 12, name: "PIONEER IMPLANT IV", status: "Active", brandId: 3 },
    // Neobiotech models
    { id: 13, name: "IS-II Active", status: "Active", brandId: 4 },
    { id: 14, name: "IS-III Active", status: "Active", brandId: 4 },
    { id: 15, name: "IS-II Active S-Narrow", status: "Active", brandId: 4 },
    { id: 16, name: "IS-III Active S-Narrow", status: "Active", brandId: 4 },
    { id: 17, name: "IT-III Active", status: "Active", brandId: 4 },
    // Neobiotech MAX models
    { id: 18, name: "MAX IMPLANT I", status: "Active", brandId: 5 },
    { id: 19, name: "MAX IMPLANT II", status: "Active", brandId: 5 },
    { id: 20, name: "MAX IMPLANT III", status: "Active", brandId: 5 },
    { id: 21, name: "MAX IMPLANT IV", status: "Active", brandId: 5 },
    { id: 22, name: "MAX IMPLANT V", status: "Active", brandId: 5 },
    // Neobiotech NURI models
    { id: 23, name: "NURI IMPLANT I", status: "Active", brandId: 6 },
    { id: 24, name: "NURI IMPLANT II", status: "Active", brandId: 6 },
    { id: 25, name: "NURI IMPLANT III", status: "Active", brandId: 6 },
    { id: 26, name: "NURI IMPLANT IV", status: "Active", brandId: 6 },
    { id: 27, name: "NURI IMPLANT V", status: "Active", brandId: 6 },
    // OSSTEM TS models
    { id: 28, name: "SSII", status: "Active", brandId: 7 },
    { id: 29, name: "SSIII", status: "Active", brandId: 7 },
    { id: 30, name: "TS BONE LEVEL", status: "Active", brandId: 7 },
    { id: 31, name: "TS TISSUE LEVEL", status: "Active", brandId: 7 },
    { id: 32, name: "TS HYBRID", status: "Active", brandId: 7 },
    // OSSTEM TSX models
    { id: 33, name: "TSX NARROW", status: "Active", brandId: 8 },
    { id: 34, name: "TSX STANDARD", status: "Active", brandId: 8 },
    { id: 35, name: "TSX WIDE", status: "Active", brandId: 8 },
    { id: 36, name: "TSX SHORT", status: "Active", brandId: 8 },
    { id: 37, name: "TSX LONG", status: "Active", brandId: 8 },
    // OSSTEM TUA models
    { id: 38, name: "TUA IMPLANT I", status: "Active", brandId: 9 },
    { id: 39, name: "TUA IMPLANT II", status: "Active", brandId: 9 },
    { id: 40, name: "TUA IMPLANT III", status: "Active", brandId: 9 },
    { id: 41, name: "TUA IMPLANT IV", status: "Active", brandId: 9 },
    { id: 42, name: "TUA IMPLANT V", status: "Active", brandId: 9 },
    // Dentium IMPLANTIUM models
    { id: 43, name: "IMPLANTIUM STANDARD", status: "Active", brandId: 10 },
    { id: 44, name: "IMPLANTIUM PLUS", status: "Active", brandId: 10 },
    // Dentium ASTRA models
    { id: 45, name: "ASTRA TECH I", status: "Active", brandId: 11 },
    { id: 46, name: "ASTRA TECH II", status: "Active", brandId: 11 },
    // Dentium XIVE models
    { id: 47, name: "XIVE IMPLANT", status: "Active", brandId: 12 },
    { id: 48, name: "XIVE PLUS", status: "Active", brandId: 12 },
  ],
  country: [
    { id: 1, name: "United States", status: "Active" },
    { id: 2, name: "Germany", status: "Active" },
    { id: 3, name: "South Korea", status: "Active" },
    { id: 4, name: "Switzerland", status: "Active" },
    // Asia - Southeast
    { id: 5, name: "Thailand", status: "Inactive" },
    { id: 6, name: "Vietnam", status: "Inactive" },
    { id: 7, name: "Philippines", status: "Inactive" },
    { id: 8, name: "Indonesia", status: "Inactive" },
    { id: 9, name: "Malaysia", status: "Inactive" },
    { id: 10, name: "Singapore", status: "Inactive" },
    { id: 11, name: "Cambodia", status: "Inactive" },
    { id: 12, name: "Laos", status: "Inactive" },
    { id: 13, name: "Myanmar", status: "Inactive" },
    { id: 14, name: "Brunei", status: "Inactive" },
    { id: 15, name: "East Timor", status: "Inactive" },
    // Asia - East
    { id: 16, name: "Japan", status: "Inactive" },
    { id: 17, name: "China", status: "Inactive" },
    { id: 18, name: "Taiwan", status: "Inactive" },
    { id: 19, name: "Hong Kong", status: "Inactive" },
    { id: 20, name: "Macau", status: "Inactive" },
    { id: 21, name: "Mongolia", status: "Inactive" },
    // Asia - South
    { id: 22, name: "India", status: "Inactive" },
    { id: 23, name: "Pakistan", status: "Inactive" },
    { id: 24, name: "Bangladesh", status: "Inactive" },
    { id: 25, name: "Nepal", status: "Inactive" },
    { id: 26, name: "Bhutan", status: "Inactive" },
    { id: 27, name: "Sri Lanka", status: "Inactive" },
    { id: 28, name: "Maldives", status: "Inactive" },
    // Asia - Central
    { id: 29, name: "Kazakhstan", status: "Inactive" },
    { id: 30, name: "Uzbekistan", status: "Inactive" },
    { id: 31, name: "Turkmenistan", status: "Inactive" },
    { id: 32, name: "Kyrgyzstan", status: "Inactive" },
    { id: 33, name: "Tajikistan", status: "Inactive" },
    // Asia - West/Middle East
    { id: 34, name: "Afghanistan", status: "Inactive" },
    { id: 35, name: "Iran", status: "Inactive" },
    { id: 36, name: "Iraq", status: "Inactive" },
    { id: 37, name: "Saudi Arabia", status: "Inactive" },
    { id: 38, name: "Yemen", status: "Inactive" },
    { id: 39, name: "Oman", status: "Inactive" },
    { id: 40, name: "United Arab Emirates", status: "Inactive" },
    { id: 41, name: "Qatar", status: "Inactive" },
    { id: 42, name: "Bahrain", status: "Inactive" },
    { id: 43, name: "Kuwait", status: "Inactive" },
    { id: 44, name: "Jordan", status: "Inactive" },
    { id: 45, name: "Lebanon", status: "Inactive" },
    { id: 46, name: "Syria", status: "Inactive" },
    { id: 47, name: "Israel", status: "Inactive" },
    { id: 48, name: "Palestine", status: "Inactive" },
    // Asia - Other
    { id: 49, name: "North Korea", status: "Inactive" },
    { id: 50, name: "Turkey", status: "Inactive" },
    // Europe - Western
    { id: 51, name: "United Kingdom", status: "Inactive" },
    { id: 52, name: "France", status: "Inactive" },
    { id: 53, name: "Belgium", status: "Inactive" },
    { id: 54, name: "Netherlands", status: "Inactive" },
    { id: 55, name: "Luxembourg", status: "Inactive" },
    { id: 56, name: "Ireland", status: "Inactive" },
    // Europe - Southern
    { id: 57, name: "Italy", status: "Inactive" },
    { id: 58, name: "Spain", status: "Inactive" },
    { id: 59, name: "Portugal", status: "Inactive" },
    { id: 60, name: "Greece", status: "Inactive" },
    { id: 61, name: "Cyprus", status: "Inactive" },
    { id: 62, name: "Malta", status: "Inactive" },
    // Europe - Northern
    { id: 63, name: "Sweden", status: "Inactive" },
    { id: 64, name: "Denmark", status: "Inactive" },
    { id: 65, name: "Norway", status: "Inactive" },
    { id: 66, name: "Finland", status: "Inactive" },
    { id: 67, name: "Iceland", status: "Inactive" },
    // Europe - Central
    { id: 68, name: "Austria", status: "Inactive" },
    { id: 69, name: "Czech Republic", status: "Inactive" },
    { id: 70, name: "Slovakia", status: "Inactive" },
    { id: 71, name: "Hungary", status: "Inactive" },
    { id: 72, name: "Poland", status: "Inactive" },
    // Europe - Eastern
    { id: 73, name: "Russia", status: "Inactive" },
    { id: 74, name: "Ukraine", status: "Inactive" },
    { id: 75, name: "Belarus", status: "Inactive" },
    { id: 76, name: "Moldova", status: "Inactive" },
    // Europe - Southeastern
    { id: 77, name: "Romania", status: "Inactive" },
    { id: 78, name: "Bulgaria", status: "Inactive" },
    { id: 79, name: "Serbia", status: "Inactive" },
    { id: 80, name: "Croatia", status: "Inactive" },
    { id: 81, name: "Slovenia", status: "Inactive" },
    { id: 82, name: "Bosnia and Herzegovina", status: "Inactive" },
    { id: 83, name: "Montenegro", status: "Inactive" },
    { id: 84, name: "Albania", status: "Inactive" },
    { id: 85, name: "North Macedonia", status: "Inactive" },
    // Europe - Caucasus/West Asia
    { id: 86, name: "Georgia", status: "Inactive" },
    { id: 87, name: "Armenia", status: "Inactive" },
    { id: 88, name: "Azerbaijan", status: "Inactive" },
    // Africa - North
    { id: 89, name: "Egypt", status: "Inactive" },
    { id: 90, name: "Libya", status: "Inactive" },
    { id: 91, name: "Tunisia", status: "Inactive" },
    { id: 92, name: "Algeria", status: "Inactive" },
    { id: 93, name: "Morocco", status: "Inactive" },
    { id: 94, name: "Sudan", status: "Inactive" },
    // Africa - West
    { id: 95, name: "Mauritania", status: "Inactive" },
    { id: 96, name: "Senegal", status: "Inactive" },
    { id: 97, name: "Gambia", status: "Inactive" },
    { id: 98, name: "Guinea-Bissau", status: "Inactive" },
    { id: 99, name: "Guinea", status: "Inactive" },
    { id: 100, name: "Sierra Leone", status: "Inactive" },
    { id: 101, name: "Liberia", status: "Inactive" },
    { id: 102, name: "Mali", status: "Inactive" },
    { id: 103, name: "Burkina Faso", status: "Inactive" },
    { id: 104, name: "Ivory Coast", status: "Inactive" },
    { id: 105, name: "Ghana", status: "Inactive" },
    { id: 106, name: "Togo", status: "Inactive" },
    { id: 107, name: "Benin", status: "Inactive" },
    { id: 108, name: "Niger", status: "Inactive" },
    { id: 109, name: "Nigeria", status: "Inactive" },
    // Africa - Central
    { id: 110, name: "Chad", status: "Inactive" },
    { id: 111, name: "Central African Republic", status: "Inactive" },
    { id: 112, name: "Cameroon", status: "Inactive" },
    { id: 113, name: "Equatorial Guinea", status: "Inactive" },
    { id: 114, name: "Gabon", status: "Inactive" },
    { id: 115, name: "Republic of the Congo", status: "Inactive" },
    { id: 116, name: "Democratic Republic of the Congo", status: "Inactive" },
    // Africa - East
    { id: 117, name: "Ethiopia", status: "Inactive" },
    { id: 118, name: "Eritrea", status: "Inactive" },
    { id: 119, name: "Djibouti", status: "Inactive" },
    { id: 120, name: "Somalia", status: "Inactive" },
    { id: 121, name: "Kenya", status: "Inactive" },
    { id: 122, name: "Uganda", status: "Inactive" },
    { id: 123, name: "Tanzania", status: "Inactive" },
    { id: 124, name: "Mozambique", status: "Inactive" },
    { id: 125, name: "Madagascar", status: "Inactive" },
    { id: 126, name: "Mauritius", status: "Inactive" },
    { id: 127, name: "Seychelles", status: "Inactive" },
    { id: 128, name: "Comoros", status: "Inactive" },
    // Africa - Southern
    { id: 129, name: "South Africa", status: "Inactive" },
    { id: 130, name: "Lesotho", status: "Inactive" },
    { id: 131, name: "Eswatini", status: "Inactive" },
    { id: 132, name: "Botswana", status: "Inactive" },
    { id: 133, name: "Namibia", status: "Inactive" },
    { id: 134, name: "Zimbabwe", status: "Inactive" },
    { id: 135, name: "Zambia", status: "Inactive" },
    { id: 136, name: "Malawi", status: "Inactive" },
    { id: 137, name: "Angola", status: "Inactive" },
    { id: 138, name: "Burundi", status: "Inactive" },
    { id: 139, name: "Rwanda", status: "Inactive" },
    { id: 140, name: "South Sudan", status: "Inactive" },
    // Americas - North
    { id: 141, name: "Canada", status: "Inactive" },
    { id: 142, name: "Mexico", status: "Inactive" },
    // Americas - Central
    { id: 143, name: "Guatemala", status: "Inactive" },
    { id: 144, name: "Belize", status: "Inactive" },
    { id: 145, name: "El Salvador", status: "Inactive" },
    { id: 146, name: "Honduras", status: "Inactive" },
    { id: 147, name: "Nicaragua", status: "Inactive" },
    { id: 148, name: "Costa Rica", status: "Inactive" },
    { id: 149, name: "Panama", status: "Inactive" },
    // Americas - Caribbean
    { id: 150, name: "Bahamas", status: "Inactive" },
    { id: 151, name: "Cuba", status: "Inactive" },
    { id: 152, name: "Dominican Republic", status: "Inactive" },
    { id: 153, name: "Haiti", status: "Inactive" },
    { id: 154, name: "Jamaica", status: "Inactive" },
    { id: 155, name: "Trinidad and Tobago", status: "Inactive" },
    { id: 156, name: "Barbados", status: "Inactive" },
    { id: 157, name: "Saint Lucia", status: "Inactive" },
    { id: 158, name: "Grenada", status: "Inactive" },
    { id: 159, name: "Saint Vincent and the Grenadines", status: "Inactive" },
    { id: 160, name: "Antigua and Barbuda", status: "Inactive" },
    { id: 161, name: "Saint Kitts and Nevis", status: "Inactive" },
    { id: 162, name: "Dominica", status: "Inactive" },
    // Americas - South
    { id: 163, name: "Colombia", status: "Inactive" },
    { id: 164, name: "Venezuela", status: "Inactive" },
    { id: 165, name: "Guyana", status: "Inactive" },
    { id: 166, name: "Suriname", status: "Inactive" },
    { id: 167, name: "Ecuador", status: "Inactive" },
    { id: 168, name: "Peru", status: "Inactive" },
    { id: 169, name: "Brazil", status: "Inactive" },
    { id: 170, name: "Bolivia", status: "Inactive" },
    { id: 171, name: "Paraguay", status: "Inactive" },
    { id: 172, name: "Uruguay", status: "Inactive" },
    { id: 173, name: "Argentina", status: "Inactive" },
    { id: 174, name: "Chile", status: "Inactive" },
    // Europe - Additional
    { id: 175, name: "Liechtenstein", status: "Inactive" },
    { id: 176, name: "Monaco", status: "Inactive" },
    { id: 177, name: "San Marino", status: "Inactive" },
    { id: 178, name: "Andorra", status: "Inactive" },
    { id: 179, name: "Latvia", status: "Inactive" },
    { id: 180, name: "Lithuania", status: "Inactive" },
    { id: 181, name: "Estonia", status: "Inactive" },
    { id: 182, name: "Kosovo", status: "Inactive" },
    // Oceania
    { id: 183, name: "Australia", status: "Inactive" },
    { id: 184, name: "New Zealand", status: "Inactive" },
    { id: 185, name: "Fiji", status: "Inactive" },
    { id: 186, name: "Samoa", status: "Inactive" },
    { id: 187, name: "Solomon Islands", status: "Inactive" },
    { id: 188, name: "Kiribati", status: "Inactive" },
    { id: 189, name: "Marshall Islands", status: "Inactive" },
    { id: 190, name: "Micronesia", status: "Inactive" },
    { id: 191, name: "Nauru", status: "Inactive" },
    { id: 192, name: "Palau", status: "Inactive" },
    { id: 193, name: "Papua New Guinea", status: "Inactive" },
    { id: 194, name: "Tonga", status: "Inactive" },
    { id: 195, name: "Tuvalu", status: "Inactive" },
  ],
  level: [
    { id: 1, name: "Bone Level", status: "Active" },
    { id: 2, name: "Tissue Level", status: "Active" },
    { id: 3, name: "Bone-level / submerged  Level", status: "Active" },
    { id: 4, name: "Tissue Tissue-level / non-submerged", status: "Active" },
  ],
  connectionType: [
    { id: 1, name: "Conical internal connection (Morse taper 7.5°)", status: "Active" },
    { id: 2, name: "Tube-in-Tube®", status: "Active" },
    { id: 3, name: "Internal M1.6", status: "Active" },
    { id: 4, name: "Internal 3.1 Octa", status: "Active" },
    { id: 5, name: "Internal conical", status: "Active" },
    { id: 6, name: "Internal conical connection ", status: "Active" },
  ],
  connectionShape: [
    { id: 1, name: "Conical connection with three positioning grooves", status: "Active" },
    { id: 2, name: "Internal Hex + Two Conical Contact", status: "Active" },
    { id: 3, name: "Internal Hex (reinforced platform)", status: "Active" },
    { id: 4, name: "Cylindrical design with three grooves and three cams", status: "Active" },
    { id: 5, name: "Cylindrical configuration with three symmetrically", status: "Active" },
    { id: 6, name: "Narrow internal Hex ", status: "Active" },
    { id: 7, name: "Octagon internal", status: "Active" },
    { id: 8, name: "Internal octa 8° tapered", status: "Active" },
    { id: 9, name: "Internal hex 11° tapered", status: "Active" },
    { id: 10, name: "Internal hex", status: "Active" },
  ],
  screwdriverShape: [
    { id: 1, name: "Hex", status: "Active" },
    { id: 2, name: "1.2 Hex", status: "Active" },
    { id: 3, name: "1.28 mm Hex", status: "Active" },
  ],
  headShape: [
    { id: 1, name: "Cylindrical neck with a 0.4 mm machined collar (Promote® plus surface).", status: "Active" },
    { id: 2, name: "Cylindrical neck with 1.4 mm", status: "Active" },
    { id: 3, name: "Cylindrical neck with 0.4 mm", status: "Active" },
    { id: 4, name: "Platform switching, BioSeal 0.5 mm", status: "Active" },
    { id: 5, name: "Micro-groove, thickened platform", status: "Active" },
    { id: 6, name: "Narrow head design", status: "Active" },
    { id: 7, name: "Micro-groove narrow platform", status: "Active" },
    { id: 8, name: "Platform switching", status: "Active" },
    { id: 9, name: "Flat-bone-level platform with internal octane", status: "Active" },
    { id: 10, name: "Flat-bone-level platform with internal octa", status: "Active" },
    { id: 11, name: "Bone-level platform with internal hex", status: "Active" },
    { id: 12, name: "Milled beveled collar", status: "Active" },
  ],
  bodyShape: [
    { id: 1, name: "Tapered Body", status: "Active" },
    { id: 2, name: "Cylindrical", status: "Active" },
    { id: 3, name: "Straight Body", status: "Active" },
    { id: 4, name: "Slim, tapered", status: "Active" },
    { id: 5, name: "Tapered body with double threaded design ", status: "Active" },
    { id: 6, name: "Tapered body with double threaded design + 3 self-tapping blades", status: "Active" },
    
  ],
  apexShape: [
    { id: 1, name: "Cutting apex", status: "Active" },
    { id: 2, name: "Flat", status: "Active" },
    { id: 3, name: "Self-tapping", status: "Active" },
    { id: 4, name: "Sharp, self tapping apex", status: "Active" },
    { id: 5, name: "Dome shape", status: "Active" },
    { id: 6, name: "High initial fixation apex", status: "Active" },
    { id: 7, name: "Cutting apex", status: "Active" },
  ],
  officialDistributor: [
    { id: 1, countryId: 1, name: "ABC Dental Supply", status: "Active" },
    { id: 2, countryId: 1, name: "XYZ Medical Co.", status: "Active" },
    { id: 3, countryId: 2, name: "Dental Plus GmbH", status: "Active" },
    { id: 4, countryId: 3, name: "Korea Dental Group", status: "Active" },
    { id: 5, countryId: 4, name: "Swiss Dental AG", status: "Active" },
    { id: 6, countryId: 5, name: "Thai Dental Center", status: "Inactive" },
    { id: 7, countryId: 6, name: "Vietnam Dental Supply", status: "Inactive" },
    { id: 8, countryId: 7, name: "Philippines Dental Co.", status: "Inactive" },
    { id: 9, countryId: 8, name: "Indonesia Dental Group", status: "Inactive" },
    { id: 10, countryId: 9, name: "Malaysia Dental Import", status: "Inactive" },
    { id: 11, countryId: 10, name: "Singapore Dental Solutions", status: "Inactive" },
    { id: 12, countryId: 11, name: "Cambodia Dental Supply", status: "Inactive" },
    { id: 13, countryId: 12, name: "Laos Dental Center", status: "Inactive" },
    { id: 14, countryId: 13, name: "Myanmar Dental Group", status: "Inactive" },
    { id: 15, countryId: 14, name: "Brunei Dental Supply", status: "Inactive" },
    { id: 16, countryId: 15, name: "East Timor Dental Co.", status: "Inactive" },
    { id: 17, countryId: 16, name: "Japan Dental Supply", status: "Inactive" },
    { id: 18, countryId: 17, name: "China Dental Group", status: "Inactive" },
    { id: 19, countryId: 18, name: "Taiwan Dental Co.", status: "Inactive" },
    { id: 20, countryId: 19, name: "Hong Kong Dental Supply", status: "Inactive" },
    { id: 21, countryId: 20, name: "Macau Dental Center", status: "Inactive" },
    { id: 22, countryId: 21, name: "Mongolia Dental Group", status: "Inactive" },
    { id: 23, countryId: 22, name: "India Dental Supply", status: "Inactive" },
    { id: 24, countryId: 23, name: "Pakistan Dental Co.", status: "Inactive" },
    { id: 25, countryId: 24, name: "Bangladesh Dental Supply", status: "Inactive" },
    { id: 26, countryId: 25, name: "Nepal Dental Center", status: "Inactive" },
    { id: 27, countryId: 26, name: "Bhutan Dental Group", status: "Inactive" },
    { id: 28, countryId: 27, name: "Sri Lanka Dental Supply", status: "Inactive" },
    { id: 29, countryId: 28, name: "Maldives Dental Co.", status: "Inactive" },
    { id: 30, countryId: 29, name: "Kazakhstan Dental Supply", status: "Inactive" },
    { id: 31, countryId: 30, name: "Uzbekistan Dental Co.", status: "Inactive" },
    { id: 32, countryId: 31, name: "Turkmenistan Dental Group", status: "Inactive" },
    { id: 33, countryId: 32, name: "Kyrgyzstan Dental Supply", status: "Inactive" },
    { id: 34, countryId: 33, name: "Tajikistan Dental Co.", status: "Inactive" },
    { id: 35, countryId: 34, name: "Afghanistan Dental Supply", status: "Inactive" },
    { id: 36, countryId: 35, name: "Iran Dental Group", status: "Inactive" },
    { id: 37, countryId: 36, name: "Iraq Dental Supply", status: "Inactive" },
    { id: 38, countryId: 37, name: "Saudi Arabia Dental Co.", status: "Inactive" },
    { id: 39, countryId: 38, name: "Yemen Dental Supply", status: "Inactive" },
    { id: 40, countryId: 39, name: "Oman Dental Center", status: "Inactive" },
    { id: 41, countryId: 40, name: "UAE Dental Group", status: "Inactive" },
    { id: 42, countryId: 41, name: "Qatar Dental Supply", status: "Inactive" },
    { id: 43, countryId: 42, name: "Bahrain Dental Co.", status: "Inactive" },
    { id: 44, countryId: 43, name: "Kuwait Dental Supply", status: "Inactive" },
    { id: 45, countryId: 44, name: "Jordan Dental Center", status: "Inactive" },
    { id: 46, countryId: 45, name: "Lebanon Dental Group", status: "Inactive" },
    { id: 47, countryId: 46, name: "Syria Dental Supply", status: "Inactive" },
    { id: 48, countryId: 47, name: "Israel Dental Co.", status: "Inactive" },
    { id: 49, countryId: 48, name: "Palestine Dental Supply", status: "Inactive" },
    { id: 50, countryId: 49, name: "North Korea Dental Group", status: "Inactive" },
    { id: 51, countryId: 50, name: "Turkey Dental Supply", status: "Inactive" },
    { id: 52, countryId: 51, name: "UK Dental Supply", status: "Inactive" },
    { id: 53, countryId: 52, name: "France Dental Group", status: "Inactive" },
    { id: 54, countryId: 53, name: "Belgium Dental Co.", status: "Inactive" },
    { id: 55, countryId: 54, name: "Netherlands Dental Supply", status: "Inactive" },
    { id: 56, countryId: 55, name: "Luxembourg Dental Center", status: "Inactive" },
    { id: 57, countryId: 56, name: "Ireland Dental Group", status: "Inactive" },
    { id: 58, countryId: 57, name: "Italy Dental Supply", status: "Inactive" },
    { id: 59, countryId: 58, name: "Spain Dental Co.", status: "Inactive" },
    { id: 60, countryId: 59, name: "Portugal Dental Supply", status: "Inactive" },
    { id: 61, countryId: 60, name: "Greece Dental Center", status: "Inactive" },
    { id: 62, countryId: 61, name: "Cyprus Dental Group", status: "Inactive" },
    { id: 63, countryId: 62, name: "Malta Dental Supply", status: "Inactive" },
    { id: 64, countryId: 63, name: "Sweden Dental Co.", status: "Inactive" },
    { id: 65, countryId: 64, name: "Denmark Dental Supply", status: "Inactive" },
    { id: 66, countryId: 65, name: "Norway Dental Center", status: "Inactive" },
    { id: 67, countryId: 66, name: "Finland Dental Group", status: "Inactive" },
    { id: 68, countryId: 67, name: "Iceland Dental Supply", status: "Inactive" },
    { id: 69, countryId: 68, name: "Austria Dental Co.", status: "Inactive" },
    { id: 70, countryId: 69, name: "Czech Republic Dental Supply", status: "Inactive" },
    { id: 71, countryId: 70, name: "Slovakia Dental Center", status: "Inactive" },
    { id: 72, countryId: 71, name: "Hungary Dental Group", status: "Inactive" },
    { id: 73, countryId: 72, name: "Poland Dental Supply", status: "Inactive" },
    { id: 74, countryId: 73, name: "Russia Dental Co.", status: "Inactive" },
    { id: 75, countryId: 74, name: "Ukraine Dental Supply", status: "Inactive" },
    { id: 76, countryId: 75, name: "Belarus Dental Center", status: "Inactive" },
    { id: 77, countryId: 76, name: "Moldova Dental Group", status: "Inactive" },
    { id: 78, countryId: 77, name: "Romania Dental Supply", status: "Inactive" },
    { id: 79, countryId: 78, name: "Bulgaria Dental Co.", status: "Inactive" },
    { id: 80, countryId: 79, name: "Serbia Dental Supply", status: "Inactive" },
    { id: 81, countryId: 80, name: "Croatia Dental Center", status: "Inactive" },
    { id: 82, countryId: 81, name: "Slovenia Dental Group", status: "Inactive" },
    { id: 83, countryId: 82, name: "Bosnia Dental Supply", status: "Inactive" },
    { id: 84, countryId: 83, name: "Montenegro Dental Co.", status: "Inactive" },
    { id: 85, countryId: 84, name: "Albania Dental Supply", status: "Inactive" },
    { id: 86, countryId: 85, name: "North Macedonia Dental Center", status: "Inactive" },
    { id: 87, countryId: 86, name: "Georgia Dental Group", status: "Inactive" },
    { id: 88, countryId: 88, name: "Azerbaijan Dental Co.", status: "Inactive" },
    { id: 89, countryId: 89, name: "Egypt Dental Supply", status: "Inactive" },
    { id: 90, countryId: 90, name: "Libya Dental Co.", status: "Inactive" },
    { id: 91, countryId: 91, name: "Tunisia Dental Supply", status: "Inactive" },
    { id: 92, countryId: 92, name: "Algeria Dental Group", status: "Inactive" },
    { id: 93, countryId: 93, name: "Morocco Dental Co.", status: "Inactive" },
    { id: 94, countryId: 94, name: "Sudan Dental Supply", status: "Inactive" },
    { id: 95, countryId: 95, name: "Mauritania Dental Group", status: "Inactive" },
    { id: 96, countryId: 96, name: "Senegal Dental Supply", status: "Inactive" },
    { id: 97, countryId: 97, name: "Gambia Dental Co.", status: "Inactive" },
    { id: 98, countryId: 98, name: "Guinea-Bissau Dental Supply", status: "Inactive" },
    { id: 99, countryId: 99, name: "Guinea Dental Group", status: "Inactive" },
    { id: 100, countryId: 100, name: "Sierra Leone Dental Supply", status: "Inactive" },
    { id: 101, countryId: 101, name: "Liberia Dental Co.", status: "Inactive" },
    { id: 102, countryId: 102, name: "Mali Dental Supply", status: "Inactive" },
    { id: 103, countryId: 103, name: "Burkina Faso Dental Group", status: "Inactive" },
    { id: 104, countryId: 104, name: "Ivory Coast Dental Supply", status: "Inactive" },
    { id: 105, countryId: 105, name: "Ghana Dental Co.", status: "Inactive" },
    { id: 106, countryId: 106, name: "Togo Dental Supply", status: "Inactive" },
    { id: 107, countryId: 107, name: "Benin Dental Group", status: "Inactive" },
    { id: 108, countryId: 108, name: "Niger Dental Supply", status: "Inactive" },
    { id: 109, countryId: 109, name: "Nigeria Dental Co.", status: "Inactive" },
    { id: 110, countryId: 110, name: "Chad Dental Supply", status: "Inactive" },
    { id: 111, countryId: 111, name: "Central African Republic Dental Group", status: "Inactive" },
    { id: 112, countryId: 112, name: "Cameroon Dental Supply", status: "Inactive" },
    { id: 113, countryId: 113, name: "Equatorial Guinea Dental Co.", status: "Inactive" },
    { id: 114, countryId: 114, name: "Gabon Dental Supply", status: "Inactive" },
    { id: 115, countryId: 115, name: "Republic of the Congo Dental Group", status: "Inactive" },
    { id: 116, countryId: 116, name: "Democratic Republic of the Congo Dental Supply", status: "Inactive" },
    { id: 117, countryId: 117, name: "Ethiopia Dental Co.", status: "Inactive" },
    { id: 118, countryId: 118, name: "Eritrea Dental Supply", status: "Inactive" },
    { id: 119, countryId: 119, name: "Djibouti Dental Group", status: "Inactive" },
    { id: 120, countryId: 120, name: "Somalia Dental Supply", status: "Inactive" },
    { id: 121, countryId: 121, name: "Kenya Dental Co.", status: "Inactive" },
    { id: 122, countryId: 122, name: "Uganda Dental Supply", status: "Inactive" },
    { id: 123, countryId: 123, name: "Tanzania Dental Group", status: "Inactive" },
    { id: 124, countryId: 124, name: "Mozambique Dental Supply", status: "Inactive" },
    { id: 125, countryId: 125, name: "Madagascar Dental Co.", status: "Inactive" },
    { id: 126, countryId: 126, name: "Mauritius Dental Supply", status: "Inactive" },
    { id: 127, countryId: 127, name: "Seychelles Dental Group", status: "Inactive" },
    { id: 128, countryId: 128, name: "Comoros Dental Supply", status: "Inactive" },
    { id: 129, countryId: 129, name: "South Africa Dental Co.", status: "Inactive" },
    { id: 130, countryId: 130, name: "Lesotho Dental Supply", status: "Inactive" },
    { id: 131, countryId: 131, name: "Eswatini Dental Group", status: "Inactive" },
    { id: 132, countryId: 132, name: "Botswana Dental Supply", status: "Inactive" },
    { id: 133, countryId: 133, name: "Namibia Dental Co.", status: "Inactive" },
    { id: 134, countryId: 134, name: "Zimbabwe Dental Supply", status: "Inactive" },
    { id: 135, countryId: 135, name: "Zambia Dental Group", status: "Inactive" },
    { id: 136, countryId: 136, name: "Malawi Dental Supply", status: "Inactive" },
    { id: 137, countryId: 137, name: "Angola Dental Co.", status: "Inactive" },
    { id: 138, countryId: 138, name: "Burundi Dental Supply", status: "Inactive" },
    { id: 139, countryId: 139, name: "Rwanda Dental Group", status: "Inactive" },
    { id: 140, countryId: 140, name: "South Sudan Dental Supply", status: "Inactive" },
    { id: 141, countryId: 141, name: "Canada Dental Co.", status: "Inactive" },
    { id: 142, countryId: 142, name: "Mexico Dental Supply", status: "Inactive" },
    { id: 143, countryId: 143, name: "Guatemala Dental Group", status: "Inactive" },
    { id: 144, countryId: 144, name: "Belize Dental Supply", status: "Inactive" },
    { id: 145, countryId: 145, name: "El Salvador Dental Co.", status: "Inactive" },
    { id: 146, countryId: 146, name: "Honduras Dental Supply", status: "Inactive" },
    { id: 147, countryId: 147, name: "Nicaragua Dental Group", status: "Inactive" },
    { id: 148, countryId: 148, name: "Costa Rica Dental Supply", status: "Inactive" },
    { id: 149, countryId: 149, name: "Panama Dental Co.", status: "Inactive" },
    { id: 150, countryId: 150, name: "Bahamas Dental Supply", status: "Inactive" },
    { id: 151, countryId: 151, name: "Cuba Dental Group", status: "Inactive" },
    { id: 152, countryId: 152, name: "Dominican Republic Dental Supply", status: "Inactive" },
    { id: 153, countryId: 153, name: "Haiti Dental Co.", status: "Inactive" },
    { id: 154, countryId: 154, name: "Jamaica Dental Supply", status: "Inactive" },
    { id: 155, countryId: 155, name: "Trinidad and Tobago Dental Group", status: "Inactive" },
    { id: 156, countryId: 156, name: "Barbados Dental Supply", status: "Inactive" },
    { id: 157, countryId: 157, name: "Saint Lucia Dental Co.", status: "Inactive" },
    { id: 158, countryId: 158, name: "Grenada Dental Supply", status: "Inactive" },
    { id: 159, countryId: 159, name: "Saint Vincent and the Grenadines Dental Group", status: "Inactive" },
    { id: 160, countryId: 160, name: "Antigua and Barbuda Dental Supply", status: "Inactive" },
    { id: 161, countryId: 161, name: "Saint Kitts and Nevis Dental Co.", status: "Inactive" },
    { id: 162, countryId: 162, name: "Dominica Dental Supply", status: "Inactive" },
    { id: 163, countryId: 163, name: "Colombia Dental Group", status: "Inactive" },
    { id: 164, countryId: 164, name: "Venezuela Dental Supply", status: "Inactive" },
    { id: 165, countryId: 165, name: "Guyana Dental Co.", status: "Inactive" },
    { id: 166, countryId: 166, name: "Suriname Dental Supply", status: "Inactive" },
    { id: 167, countryId: 167, name: "Ecuador Dental Group", status: "Inactive" },
    { id: 168, countryId: 168, name: "Peru Dental Supply", status: "Inactive" },
    { id: 169, countryId: 169, name: "Brazil Dental Co.", status: "Inactive" },
    { id: 170, countryId: 170, name: "Bolivia Dental Supply", status: "Inactive" },
    { id: 171, countryId: 171, name: "Paraguay Dental Group", status: "Inactive" },
    { id: 172, countryId: 172, name: "Uruguay Dental Supply", status: "Inactive" },
    { id: 173, countryId: 173, name: "Argentina Dental Co.", status: "Inactive" },
    { id: 174, countryId: 174, name: "Chile Dental Supply", status: "Inactive" },
    { id: 175, countryId: 175, name: "Liechtenstein Dental Group", status: "Inactive" },
    { id: 176, countryId: 176, name: "Monaco Dental Supply", status: "Inactive" },
    { id: 177, countryId: 177, name: "San Marino Dental Co.", status: "Inactive" },
    { id: 178, countryId: 178, name: "Andorra Dental Supply", status: "Inactive" },
    { id: 179, countryId: 179, name: "Latvia Dental Group", status: "Inactive" },
    { id: 180, countryId: 180, name: "Lithuania Dental Supply", status: "Inactive" },
    { id: 181, countryId: 181, name: "Estonia Dental Co.", status: "Inactive" },
    { id: 182, countryId: 182, name: "Kosovo Dental Supply", status: "Inactive" },
    { id: 183, countryId: 183, name: "Australia Dental Group", status: "Inactive" },
    { id: 184, countryId: 184, name: "New Zealand Dental Supply", status: "Inactive" },
    { id: 185, countryId: 185, name: "Fiji Dental Co.", status: "Inactive" },
    { id: 186, countryId: 186, name: "Samoa Dental Supply", status: "Inactive" },
    { id: 187, countryId: 187, name: "Solomon Islands Dental Group", status: "Inactive" },
    { id: 188, countryId: 188, name: "Kiribati Dental Supply", status: "Inactive" },
    { id: 189, countryId: 189, name: "Marshall Islands Dental Co.", status: "Inactive" },
    { id: 190, countryId: 190, name: "Micronesia Dental Supply", status: "Inactive" },
    { id: 191, countryId: 191, name: "Nauru Dental Group", status: "Inactive" },
    { id: 192, countryId: 192, name: "Palau Dental Supply", status: "Inactive" },
    { id: 193, countryId: 193, name: "Papua New Guinea Dental Co.", status: "Inactive" },
    { id: 194, countryId: 194, name: "Tonga Dental Supply", status: "Inactive" },
    { id: 195, countryId: 195, name: "Tuvalu Dental Group", status: "Inactive" },
  ],
};

export function loadMaster() {
  const raw = localStorage.getItem(MASTER_KEY);
  const storedVersion = localStorage.getItem(MASTER_VERSION_KEY);

  console.log("🔍 loadMaster() called:", { MASTER_KEY, storedVersion, CURRENT_SEED_VERSION, rawExists: !!raw });

  // ✅ ถ้าไม่มีข้อมูล หรือ version เก่า ให้โหลด seed ใหม่
  if (!raw || storedVersion !== CURRENT_SEED_VERSION) {
    console.log(`🔄 Version mismatch or no data. Stored: ${storedVersion}, Current: ${CURRENT_SEED_VERSION}. Loading seed...`);
    console.log("📦 Seed data:", { companies: seed.company.length, levels: seed.level.length, countries: seed.country.length });
    localStorage.setItem(MASTER_KEY, JSON.stringify(seed));
    localStorage.setItem(MASTER_VERSION_KEY, CURRENT_SEED_VERSION);
    return seed;
  }

  try {
    const obj = JSON.parse(raw);
    console.log("✅ Loaded from localStorage:", { companies: obj.company?.length, levels: obj.level?.length, countries: obj.country?.length });
    return obj && typeof obj === "object" ? obj : seed;
  } catch {
    console.warn("Failed to parse stored master data, using seed");
    return seed;
  }
}

export function saveMaster(obj) {
  localStorage.setItem(MASTER_KEY, JSON.stringify(obj));
}

export function getTypeLabel(typeKey) {
  return MASTER_TYPES.find((t) => t.key === typeKey)?.label || typeKey;
}

// ✅ Helper functions สำหรับแปลง ID ↔ Name
export function getIdByName(type, name) {
  const master = loadMaster();
  const item = master[type]?.find(x => x.name === name);
  return item?.id || null;
}

export function getNameById(type, id) {
  const master = loadMaster();
  const item = master[type]?.find(x => x.id === id);
  return item?.name || "N/A";
}
